#pragma once

#include "Bitvector.h"
#include "BitvectorPrefix.h"
#include "Compact.h"
#include "Compact2.h"
#include "Compact2Aligned.h"
#include "CompactAligned.h"
#include "CompactPrefix.h"
#include "CompactWavelet.h"
#include "CompactWavelet32.h"
#include "InterleavedEPR.h"
#include "Naive.h"
#include "Sdsl_wt_bldc.h"
#include "Sdsl_wt_epr.h"
#include "Wavelet.h"
