// SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
// SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
// SPDX-License-Identifier: BSD-3-Clause
#pragma once

#include "CompactBitvector.h"
#include "DenseEPRV6.h"
#include "EPRV3.h"
#include "EPRV4.h"
#include "EPRV5.h"
#include "FlattenedBitvectors2L.h"
#include "InterleavedBitvector.h"
#include "InterleavedBitvectorPrefix.h"
#include "InterleavedEPR.h"
#include "InterleavedEPRV2.h"
#include "InterleavedEPRV7.h"
#include "InterleavedWavelet.h"
#include "MultiBitvector.h"
#include "MultiBitvectorPrefix.h"
#include "MultiaryWavelet.h"
#include "NEPRV8.h"
#include "Naive.h"
#include "PairedFlattenedBitvectors2L.h"
#include "PartialPairedL0L1L2_NEPRV8.h"
#include "RunBlockEncoding.h"
#include "RunBlockEncodingV2.h"
#include "Sdsl_wt_bldc.h"
#include "Sdsl_wt_epr.h"
#include "Wavelet.h"
#include "WrappedBitvector.h"
#include "utils.h"
