name: "Windows Server 2022"

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'main'
  pull_request:

concurrency:
  group: msvc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

jobs:
  build:
    name: Windows Server 2022
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: fmc
          fetch-depth: 1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Tools on Windows
        run: |
          vcpkg integrate install
          vcpkg install fmt fmt:x64-windows
      - name: Build something requiring CL.EXE
        run: |
          mkdir fmc-build
          cd fmc-build
          cmake ../fmc -G "NMake Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
          nmake VERBOSE=1
      - name: Run tests
        run: |
          cd fmc-build
          ctest . --output-on-failure
