# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "MacOS"

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TZ: Europe/Berlin

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: macos-12
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        osname: ["MacOS 12"]
        compiler: ["gcc13 (c++20)", "gcc12 (c++20)", "gcc11 (c++20)", "gcc13 (c++20, Debug)"]

        include:
          - osname: "MacOS 12"
            os: macos-12
            cmake_flags: "-DFMC_USE_SDSL=NO"
            threads: 3

          - compiler: "gcc13 (c++20)"
            cxx: "g++-13"
            cc: "gcc-13"
            build_type: Release
            brew_pkgs: gcc@13

          - compiler: "gcc12 (c++20)"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release
            brew_pkgs: gcc@12

          - compiler: "gcc11 (c++20)"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release
            brew_pkgs: gcc@11

          - compiler: "gcc13 (c++20, Debug)"
            cxx: "g++-13"
            cc: "gcc-13"
            build_type: Debug
            brew_pkgs: gcc@13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: fmc
          fetch-depth: 1

      - name: Install Tools on Mac
        run: |
          touch ${HOME}/.activate_brew
          brew update-reset
          brew install --force-bottle --overwrite fmt boost cmake ${{ matrix.brew_pkgs }} pkg-config

      - name: Tool versions
        run: |
          source ${HOME}/.activate_brew
          cmake --version
          ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          source ${HOME}/.activate_brew
          mkdir fmc-build
          cd fmc-build
          cmake ../fmc -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.cmake_flags }}

      - name: Build tests
        run: |
          source ${HOME}/.activate_brew
          cd fmc-build
          make -k -j2

      - name: Run tests
        run: |
          source ${HOME}/.activate_brew
          cd fmc-build
          ctest . -j ${{ matrix.threads }} --output-on-failure
