name: Tests

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.23.2
  TZ: Europe/Berlin

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        osname: ["MacOS 11", "Ubuntu 22.04"]
        compiler: ["gcc12 (c++20)", "gcc11 (c++20)", "gcc10 (c++20)", "gcc12 (c++20, Debug)"]
        include:
          - osname: "Ubuntu 22.04"
            os: ubuntu-22.04
            cmake_flags: ""
          - osname: "MacOS 11"
            os: macos-11
            cmake_flags: "-DFMC_USE_SDSL=NO"

          - compiler: "gcc12 (c++20)"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release

          - compiler: "gcc11 (c++20)"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release

          - compiler: "gcc10 (c++20)"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release

          - compiler: "gcc12 (c++20, Debug)"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Debug

    steps:
      - name: Checkout TDL
        uses: actions/checkout@v3
        with:
          path: fmc
          fetch-depth: 1

      - name: Install Tools
        run: |
          brew update
          brew install fmt boost cmake gcc@10 gcc gcc@12

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir fmc-build
          cd fmc-build
          cmake ../fmc -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.cmake_flags }}

      - name: Build tests
        run: |
          cd fmc-build
          make -k -j2

      - name: Run tests
        run: |
          cd fmc-build
          ctest . -j2 --output-on-failure
