name: Tests(c++20)
on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.23.2
  TZ: Europe/Berlin

jobs:
  build:
    name: ${{ matrix.compiler }} / ${{ matrix.osname }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        osname: ["MacOS 11"]
        compiler: ["gcc12", "gcc11", "gcc10", "gcc12-debug"]
        include:
          - osname: "Ubuntu 22.04"
            os: ubuntu-22.04
            extra: ""
          - osname: "MacOS 11"
            os: macos-11
            extra: "-nostdinc++ -nodefaultlibs -lc -lc++ -lc++abi -isystem /usr/include/c++/v1 -lc++abi -lunwind -lm"
            removed: "-lgcc_s"

          - compiler: "gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release

          - compiler: "gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release

          - compiler: "gcc10"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release

          - compiler: "gcc12-debug"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Debug

    steps:
      - name: Checkout TDL
        uses: actions/checkout@v3
        with:
          path: fmc
          fetch-depth: 1

      - name: Install Tools
        run: |
          brew update
          brew install fmt boost cmake gcc@10 gcc gcc@12

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir fmc-build
          cd fmc-build
          cmake ../fmc -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                       -DCMAKE_CXX_FLAGS="-isystem $(brew --prefix)/include -L$(brew --prefix)/lib ${{ matrix.extra }}"

      - name: Build tests
        run: |
          cd fmc-build
          make -j2

      - name: Run tests
        run: |
          cd fmc-build
          ctest . -j2 --output-on-failure
