name: CI on macOS-11

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'main'
  pull_request:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.15.1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-11
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc12 (c++20)"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release

          - name: "gcc11 (c++20)"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release

          - name: "gcc10 (c++20)"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release


    steps:
      - name: Checkout TDL
        uses: actions/checkout@v2
        with:
          path: fmc
          fetch-depth: 1

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Tools
        run: |
          brew update
          brew doctor
          brew config
          brew install fmt boost cmake gcc@10 gcc gcc@12

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir fmc-build
          cd fmc-build
          cmake ../fmc -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                       -DCMAKE_CXX_FLAGS="-isystem $(brew --prefix)/include -L$(brew --prefix)/lib"

      - name: Build tests
        run: |
          cd fmc-build
          make -j2

      - name: Run tests
        run: |
          cd fmc-build
          ctest . -j2 --output-on-failure
