# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "CI"

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  NANOBENCH_SUPPRESS_WARNINGS: 1
  TZ: Europe/Berlin

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, compiler: spdx_reuse_lint}
          - {os: ubuntu-22.04, compiler: cpm_version_check}
          - {os: ubuntu-22.04, compiler: gcc12-cpp20-release}
          - {os: ubuntu-22.04, compiler: gcc13-cpp20-release}
          - {os: ubuntu-22.04, compiler: gcc14-cpp20-release}
          - {os: ubuntu-22.04, compiler: gcc14-cpp20-debug-sanitize_address}
          - {os: ubuntu-22.04, compiler: gcc14-cpp20-debug-sanitize_undefined}
          - {os: ubuntu-22.04, compiler: gcc14-cpp20-debug-sanitize_thread}
          - {os: ubuntu-22.04, compiler: gcc14-cpp20-lcov}
          - {os: ubuntu-22.04, compiler: gcc14-cpp23-release}
          - {os: ubuntu-22.04, compiler: clang16-cpp20-release}
          - {os: ubuntu-22.04, compiler: clang17-cpp20-release}
          - {os: macos-12,     compiler: gcc14-cpp20-release,      cmake_flags: "-DFMC_USE_SDSL=NO"}
          - {os: macos-12,     compiler: clang17-cpp20-release,    cmake_flags: "-DFMC_USE_SDSL=NO"}
          - {os: windows-2022, compiler: msvc-cpp20-release,       cmake_flags: "-DFMC_USE_SDSL=NO"}
          # not running any tests, since it takes to long
          - {os: windows-2022, compiler: msvc-cpp20-debug-notests, cmake_flags: "-DFMC_USE_SDSL=NO"}
          - {os: ubuntu-22.04, compiler: emscripten-cpp20-release, cmake_flags: "-DCMAKE_EXE_LINKER_FLAGS='-sALLOW_MEMORY_GROWTH=1 -sSTACK_SIZE=1000000'", cmake_cxx_flags: "-Wno-c++11-narrowing"}
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction@v9.16
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cmake_flags: ${{ matrix.cmake_flags }}
          cmake_c_flags: ${{ matrix.cmake_c_flags }}
          cmake_cxx_flags: ${{ matrix.cmake_cxx_flags }}
  final:
    runs-on: ubuntu-22.04
    name: final-pass
    needs: build
    if: always()
    steps:
      - name: Succeeded
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: CI failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
